# -*- coding: utf-8 -*-
"""PythonSesion18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XBMRuYcQxGRHnjOoT1QIh0eDaIOiUnkI

## New Section

Variables en Python
"""

nombre = 'Juan'
print('nombre:', nombre)
edad = 25
esMayor = True
IVA_1 = 0.19

#Type(x) muestra el tipo de datos de x

type(edad)
type(nombre)
type(IVA)

print('Nombre:', nombre, '. Edad:',edad)
print('Nombre: '+nombre+'. Edad: '+str(edad))
print(f'Nombre: {nombre}. Edad: {edad}')
print(IVA_1)

"""Operadores aritméticos"""

a=12
b=3

print('suma: ', a+b)
print('resta: ', a-b)
print('multiplicación: ', a*b)
print('división: ', a/b)
print('división entera: ', a//b)
print('modulo: ', a%b)
print('potencia: ', a**b)

#Operadores de incremento

a+=5
print(a)
a-=5
print(a)
a*=5
print(a)

"""Operadores de comparación"""

x = 12
y = 3

print('x es mayor que y:', x>y)
print('x es menor que y:', x<y)
print('x es mayor o igual que y:', x>=y)
print('x es menor o igual que y:', x<=y)
print('x es igual que y:', x==y)
print('x es diferente que y:', x!=y)

"""Operadores relacionales"""

condicion1 = True
condicion2 = False

condicion1 and condicion2
condicion1 or condicion2
not condicion1 and condicion2
not condicion1 or condicion2

"""Colecciones de datos: Listas"""

miLista = [10 , 20 , 'hola' , True , 3.5, 'Jose', False, 29, 3.14]
print('Tamaño: ', len(miLista))
print('Mi lista: ', miLista)

#Acceder a un elemento de la lista por su indice

print(miLista[0])
print(miLista[2])

#Actualizar el valor de la lista

miLista[3]='Buenos dias'
print('Mi lista: ', miLista)

#Agregar un elemento al final de la lista

miLista.append(500)
print('Mi lista: ', miLista)

#Agregar un elemento en una parte específica de la lista

miLista.insert(1, False)
print('Mi lista: ', miLista)

#Eliminar un elemento de la lista

del miLista[0]
print('Mi lista: ', miLista)
miLista.remove('hola')
print('Mi lista: ', miLista)

"""Programa que suma dos números"""

#int(x) convierte x a tipo entero
#floar(x) convierte x a tipo real
num1=int(input('Ingrese el primero número: '))
num2=int(input('Ingrese el segundo número: '))

suma = num1 + num2

print('El resultado de la suma es: ',suma)

"""Colecciones de datos: Diccionarios"""

# Crear el diccionario inicial con información sobre una persona
persona = {
    'nombre': 'Pedro',
    'apellido': 'Pérez',
    'edad': 23,
    'direccion': 'Calle 7',
    'empleado': True
}

# Imprimir el tamaño del diccionario y su contenido
print('Tamaño:', len(persona))
print('Persona:', persona)

# Acceder a un valor específico del diccionario
print('Dirección:', persona['direccion'])
print(f"Nombre: {persona['nombre']}")

# Modificar un valor en el diccionario
persona['edad'] = 32
print('Edad actualizada:', persona['edad'])

# Agregar un nuevo par clave-valor al diccionario
persona['profesion'] = 'Ingeniero'
print('Diccionario actualizado:', persona)