# -*- coding: utf-8 -*-
"""PythonSesion19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vNVmjP3mHfL5IKPA75IYkOEd_YXBKGzm

Condicionales
"""

#Condicionales simples
n1 = int(input('Ingrese el primer número entero: '))
n2 = int(input('Ingrese el segundo número entero: '))
if(n1==n2):
  print('Los números son iguales.')
print('Fin del programa')

#Condicionales dobles
n1 = int(input('Ingrese el primer número entero: '))
n2 = int(input('Ingrese el segundo número entero: '))
if (n1==n2):
  print('Los números son iguales.')
else:
  print('Los números son diferentes')
print('Fin del programa')

#Condicionales múltiples o anidados
numero=float(input('Ingrese un número: '))
if(numero==0):
  print('El cero es un número neutro.')
else:
  if(numero>0):
    print('El número es positivo.')
  else:
    print('El número es negativo')
print('Fin del programa')

#Programa que dice si un número es par o impar
n = int(input('Ingrese el número entero: '))
if(n%2==0):
  print(f'{n} es par')
else:
  print(f'{n} es impar')

#Programa que dice si un número positivo tiene 1. 2 o 3 cifras.
n = int(input('Ingrese un número entero positivo: '))
if (n<10):
  print(f'{n} tiene un digitos')
elif(n<100):
  print(f'{n} tiene dos digitos')
elif(n<1000):
  print(f'{n} tiene tres digitos')
else:
  print('El número está fuera del rango.')

"""While

"""

#Programa que cuenta del 1 al 10
contador=1
while(contador<=10):
  print(contador)
  contador+=1
print('Fin del programa.')

#Programa que decrementa del 10 al 1
contador=10
while(contador>=1):
  print(contador)
  contador-=1
print('Fin del programa.')

#Validar una entrada
nota = float(input('Ingrese la nota: '))
while(nota<0 and nota>0):
  nota = float(input('Concéntrese... La nota debe estar entre 0 y 10: '))
print(f'La nota es: {nota}')

"""Ciclos: For"""

#Contar los números del 1 al 10
for i in range(1,11):
  print(i)

#Mostrar los números pares del 1 al 20
for i in range(2, 21, 2):
  print(i)

#Recorrer una lista con ciclo 1era forma
numeros = [10, 30, 40, 80, 90]
for i in numeros:
  print(i)

#Recorrer una lista con ciclo 2da forma
asignaturas = ['Algoritmos', 'Desarrollo Web', 'Cálculo', 'Física']
for i in range(len(asignaturas)):
  print(asignaturas[i])

"""Programa que recibe una coordenada (x, y) que representa puntos en el plano. Se debe informar cuanto puntos estan en el primero, segundo, tercer y cuarto cuadrante."""

while(True):
  cuadrante1=cuadrante2=cuadrante3=cuadrante4=0
  n=int(input('Cuantos puntos va a ingresar: '))
  for _ in range(n):
    x=int(input('Ingrese el valor de x: '))
    y=int(input('Ingrese el valor de y: '))
    if (x>0) and (y>0):
      cuadrante1+=1
    elif (x<0) and (y>0):
      cuadrante2+=1
    elif (x<0) and (y<0):
      cuadrante3+=1
    else:
      cuadrante4+=1
  print(f'Puntos en cuadrante1: {cuadrante1}')
  print(f'Puntos en cuadrante2: {cuadrante2}')
  print(f'Puntos en cuadrante3: {cuadrante3}')
  print(f'Puntos en cuadrante4: {cuadrante4}')
  opcion=int(input('\n1. Si\n2. No\nDesea continuar?:'))
  while(opcion<1 or opcion>2):
    opcion=int(input('¡Error! Ingrese 1 o 2: '))
  if(opcion==2):
    break
  print('Fin del programa.')

"""En una empresa trabajan n empleados, sus sueldos van de 1.000.000 a 5.000.000, realice un programa que lea los sueldos de cada empleado e informe cuantos empleados cobran entre 1M y 3M y cuantos cobran mas de 3M, además muestre el valor total de la nomina.:"""

n=int(input('Ingrese el número de empleados: '))
sueldos=[]
for i in range(n):
  sueldo=float(input(f'Ingrese el sueldo del empleado{i+1}: '))
  sueldos.append(sueldo)
total1=0
total2=0
for i in sueldos:
  if(i>=1000000 and i<=3000000):
    total1+=1
  if(i>3000000):
    total2+=1
nomina=sum(sueldos)
print(f'Empleados que cobran entre 1M y 3M: {total1}')
print(f'Empleados que cobran más de 3M: {total2}')
print(f'Total nómina: {nomina}')